### PR TITLE
Fix user-facing typo: enconutered -> encountered

### PR DESCRIPTION
**Pull request by grdryn**

### CODE REVIEW

**Comment by evanshortiss** [comment]
Thanks @grdryn will publish shortly

**Comment by david-martin** [comment]
@evanshortiss has this been published yet?

**Comment by evanshortiss** [comment]
@david-martin @grdryn published as 0.2.0

**Comment by david-martin** [comment]
thanks @evanshortiss

**Comment by grdryn** [comment]
Yes, thanks a lot @evanshortiss :)

**Pull request merged**
